#!/bin/bash -x
#SBATCH --account=jiek12
#SBATCH --job-name=Coulomb
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --output=out.%j
#SBATCH --error=err.%j
#SBATCH --time=10:00:00

# *** start of job script ***
# Note: The current working directory at this point is
# the directory where sbatch was executed.

#export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
#export MPICH_NO_BUFFER_ALIAS_CHECK=1

#module purge
#module load CUDA
#module load Intel/2017.0.098-GCC-5.4.0
#module load ParaStationMPI/5.1.5-1
#module load imkl

#ml use /gpfs/software/juwels/otherstages
#ml Stages/2018b

#export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}

#module load intel-para
#module load intel-para/2018b
#module load intel-para/2018b-mt

srun /p/home/jusers/koester2/jureca/bin/supercell -i O1.cif -q -p "Na*:c=1.0" -p "Li*:c=1.0" -p "Mn*:c=4.0" -p "O*:c=-1.88888888888889" -m -n l1 -v 2 -o coulomb-ouput.out
