#!/bin/bash -x
#SBATCH --job-name=GOAC
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --output=out.%j
#SBATCH --error=err.%j
#SBATCH --time=00:30:00

export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
export OMP_NESTED=false

srun python3 ../../../../GOAC/ -f O1.cif -p "Na*:c=1.0" -p "Li*:c=1.0" -p "Mn*:c=4.0" -p "O*:c=-1.8703703703704" -s "gurobi" -n 1 -w 1
