#!/bin/bash -x
#SBATCH --job-name=GOAC
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --output=out.%j
#SBATCH --error=err.%j
#SBATCH --time=02:00:00

export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
export OMP_NESTED=true
export PYTHONUNBUFFERED=true

srun python3 ../../../../GOAC/ -f ../../LLZO.cif -e "2x2x1" -p "Li*:c=1.0" -p "La*:c=3.0" -p "Zr*:c=4.0" -p "Ta*:c=5.0" -p "O*:c=-2.0" -s "random-hybrid" -n 32 -w 25 -y options
